version: "3.9"

services:
  backend:
    build: ./backend
    container_name: hsr-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: hsr-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: hsr-redis
    restart: unless-stopped
    env_file:
      - ./backend/.env
    command: sh -c 'redis-server --requirepass "$REDIS_PASSWORD" --appendonly yes'
    volumes:
      - redis_data:/data
    networks:
      - appnet

networks:
  appnet:

volumes:
  redis_data: